# Generated by Django 4.2.20 on 2025-06-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
    ]
