# Generated by Django 4.2.20 on 2025-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
