# Generated by Django 4.2.27 on 2026-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_alter_movie_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="content_type",
            field=models.CharField(
                choices=[("film", "Film"), ("tv_show", "TV Show")],
                default="film",
                max_length=20,
            ),
        ),
    ]
